rules:
  - id: weak-password-hash
    languages: [python]
    severity: ERROR  # Spécifiez le niveau de gravité ici (en majuscules)
    message: "Weak password hash algorithm detected (MD5 or SHA-1)."
    patterns:
      - pattern: "md5"
      - pattern: "sha1"
