rules:
  - id: weak-password-hash
    languages: [python] # Spécifiez le langage du code que vous souhaitez analyser
    message: "Weak password hash algorithm detected (MD5 or SHA-1)."
    patterns:
      - pattern: "md5" # Exemple de nom de fonction ou de variable à rechercher
      - pattern: "sha1"
