name: CI pipeline
on:
  push:
    branches:
      - 'main'
    paths:
      - "Dockerfile"
      - "vulnerable-flask-app.py"
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.ref_name }}'
          token: ${{ secrets.GITLEAKS }}

      - name: Set up Gitleaks
        env:
          GITLEAKS: ${{ secrets.GITLEAKS}}
        run: |
          wget -O gitleaks https://github.com/zricethezav/gitleaks/releases/download/v7.2.0/gitleaks-linux-amd64
          chmod +x gitleaks
          ./gitleaks --repo=https://github.com/D-Z101/DevSecOps --redact

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install semgrep
          if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi

      - name: Semgrep SAST Scan
        run: |
          semgrep -c semgrep-config.yml .
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image from Dockerfile
        run: |
          docker build -t test_${{ github.run_number }}:v1 .

        
      - name: Install Trivy
        run: |
          sudo apt-get install wget
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -qy
          sudo apt-get install trivy

      - name: Run Trivy Vulnerability Scan
        run: |
           trivy python:3.10.11-slim-buster --severity HIGH,CRITICAL
           
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker tag test_${{ github.run_number }}:v1 zeyrouch/devsecopslab:v${{ github.run_number }}
          docker push zeyrouch/devsecopslab:v${{ github.run_number }}

      - name: Checkout the ENV Repo
        uses: actions/checkout@v3
        with:
          repository: 'D-Z101/DevSecOps'
          ref: 'main'
          token:  ${{ secrets.GITLEAKS}}

      - name: Set up YQ command
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64.tar.gz -O - | sudo tar xz && sudo mv yq_linux_amd64 /usr/bin/yq

      - name: Edit manifests in ENV repo
        run: |
          yq eval -i '.spec.template.spec.containers[0].image = "zeyrouch/devsecopslab:v${{ github.run_number }}"' ./kubernetes/deployment.yaml

      - name: Commit and Push to ENV repo
        run: |
          git config  user.email "diazeinebou101@gmail.com"
          git config  user.name "D-Z101"
          git commit -a -m 'Env file is updated with the new image ${{ github.ref_name }}'
          git push https://${{ secrets.GITLEAKS }}@github.com/D-Z101/DevSecOps.git
